fix: [10:12:16 ERR] [!] Error getting SirHurt version from API: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType, JsonTokenType) + 0x2b
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32, ReadOnlySpan`1, JsonElement&) + 0x3e1
   at Sirstrap.Core.RobloxVersionService.<GetSirhurtVersionAsync>d__5.MoveNext() + 0x197